### ISSUE TITLE
Artist - Title is too restrictive

### ISSUE THREAD

**Issue by frankwalter1301** [ortexx/museria-global#10]
There are a lot of different convention in naming for different genres, subgenres and underground genres that nobody knows except 3 people in the world and even if we all agree on a convention then people will not find old songs easily because they will not know how the uploader adapted the title to the chosen convention. There is the need of a smart search function.

**Comment by ortexx** [comment]
Now we have configured parameter to define titles similarity. 85% at the moment. And also a special search algorithm for comparison. Users don't need to guess the exact match. They can have some deviations. The options were picked up the way to keep balance with all storage factors. But if you could describe how exactly i can improve the logic, let me know with more details.

https://github.com/ortexx/museria/blob/master/src/utils.js - here in .getSongSimilarity() you can find the algo if necessary.

**Comment by ortexx** [comment]
Added a simple text search. Now you can find songs just typing 3(configured) or more symbols in the form.
